services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teamb_backend
    ports:
      - "8000:8000"
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./firebase-service-account.json:/firebase-service-account.json
      - ./.env:/app/.env     # 環境変数ファイル用マウント
      - ./tests:/app/tests  # テストファイル用マウント
      - ./app:/app/app      # アプリケーションコード用マウント（開発時のホットリロード）
    entrypoint:
      [
        "/bin/sh",
        "/app/wait-for-db.sh",
        "db",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

  db:
    image: postgres:17.5-alpine
    container_name: teamb_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
