services:
  backend:
    build: .
    container_name: teamb_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17.5-alpine
    container_name: teamb_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
volumes:
  postgres_data:
