"""make trial fields nullable in subscriptions

Revision ID: 653a2e9135e5
Revises: d4133314bd35
Create Date: 2025-08-20 15:24:33.262563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653a2e9135e5'
down_revision: Union[str, Sequence[str], None] = 'd4133314bd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'trial_started_at',
               existing_type=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'trial_expires_at',
               existing_type=sa.DateTime(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'trial_expires_at',
               existing_type=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('subscriptions', 'trial_started_at',
               existing_type=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
