"""初期化

Revision ID: 781571ca11e2
Revises: 1e42c6fd1d02
Create Date: 2025-08-19 07:21:11.556557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781571ca11e2'
down_revision: Union[str, Sequence[str], None] = '1e42c6fd1d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_subscriptions_user_id'), 'subscriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_subscriptions_user_id'), 'subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
