"""Make audio_file_path nullable

Revision ID: d4133314bd35
Revises: 530faaa64ab6
Create Date: 2025-08-20 03:19:47.628854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4133314bd35"
down_revision: Union[str, Sequence[str], None] = "530faaa64ab6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # audio_file_pathカラムをnullableに変更
    op.alter_column(
        "emotion_logs", "audio_file_path", existing_type=sa.String(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # audio_file_pathカラムをnot nullに戻す
    op.alter_column(
        "emotion_logs", "audio_file_path", existing_type=sa.String(), nullable=False
    )
    # ### end Alembic commands ###
