"""fix:モデルにnullable=Trueを明示的に追加

Revision ID: dcaf9fab4553
Revises: d4133314bd35
Create Date: 2025-08-20 15:08:01.482803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcaf9fab4553'
down_revision: Union[str, Sequence[str], None] = 'd4133314bd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emotion_logs', 'voice_note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('emotion_logs', 'text_file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('emotion_logs', 'audio_file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emotion_logs', 'audio_file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('emotion_logs', 'text_file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('emotion_logs', 'voice_note',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
